#   ╭──────────────────────────────────────────╮
#   │ ██╗  ██╗██╗████████╗████████╗██╗   ██╗   │
#   │ ██║ ██╔╝██║╚══██╔══╝╚══██╔══╝╚██╗ ██╔╝   │
#   │ █████╔╝ ██║   ██║      ██║    ╚████╔╝    │
#   │ ██╔═██╗ ██║   ██║      ██║     ╚██╔╝     │
#   │ ██║  ██╗██║   ██║      ██║      ██║      │
#   │ ╚═╝  ╚═╝╚═╝   ╚═╝      ╚═╝      ╚═╝      │
#   ╰──────────────────────────────────────────╯


font_size 10

background_image        /home/void/Pictures/auto_20260209_192149.png

shell /bin/fish
